---
- hosts: all
  remote_user: root

  tasks:
    - name: install chrome
      shell: |
        curl -o /private/tmp/chrome.dmg https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
        hdiutil attach -mountpoint /private/tmp/chrome -nobrowse /private/tmp/chrome.dmg
        cp -R "/private/tmp/chrome/Google Chrome.app" /Applications
        hdiutil detach /private/tmp/chrome
      args:
        creates: "/Applications/Google Chrome.app"